// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGA2h51M058DI6Z6Y9zRH5aHqmxQLq1J4',
    appId: '1:415533690944:web:f494f961a32e86feca6fa5',
    messagingSenderId: '415533690944',
    projectId: 'safenetai-84d11',
    authDomain: 'safenetai-84d11.firebaseapp.com',
    storageBucket: 'safenetai-84d11.firebasestorage.app',
    measurementId: 'G-Z0HGTM0YCZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArDvXbQxigVy9jnBp8aUgb7pASNBmIT3k',
    appId: '1:415533690944:android:b5125333770a5ef5ca6fa5',
    messagingSenderId: '415533690944',
    projectId: 'safenetai-84d11',
    storageBucket: 'safenetai-84d11.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBK96LGFiG4RXlVM109hn32R2C3-L5vxZk',
    appId: '1:415533690944:ios:a6b7788d52cfee3aca6fa5',
    messagingSenderId: '415533690944',
    projectId: 'safenetai-84d11',
    storageBucket: 'safenetai-84d11.firebasestorage.app',
    iosBundleId: 'com.example.hackathon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBK96LGFiG4RXlVM109hn32R2C3-L5vxZk',
    appId: '1:415533690944:ios:a6b7788d52cfee3aca6fa5',
    messagingSenderId: '415533690944',
    projectId: 'safenetai-84d11',
    storageBucket: 'safenetai-84d11.firebasestorage.app',
    iosBundleId: 'com.example.hackathon',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGA2h51M058DI6Z6Y9zRH5aHqmxQLq1J4',
    appId: '1:415533690944:web:fd61585bc614cf16ca6fa5',
    messagingSenderId: '415533690944',
    projectId: 'safenetai-84d11',
    authDomain: 'safenetai-84d11.firebaseapp.com',
    storageBucket: 'safenetai-84d11.firebasestorage.app',
    measurementId: 'G-N29SME7SD3',
  );
}
